// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"vote-demo/httpserver/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/results",
				Handler: GetResultsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/votes",
				Handler: GetUserVotesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vote",
				Handler: VoteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vote/revoke",
				Handler: RevokeHandler(serverCtx),
			},
		},
	)
}
