// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetResultsResponse struct {
	Results []TopicResult `json:"results"`
}

type GetUserVotesResponse struct {
	VotedTopics []string `json:"voted_topics"`
}

type RevokeRequest struct {
	Topics []string `json:"topics"`
}

type RevokeResponse struct {
	Success bool          `json:"success"`
	Message string        `json:"message"`
	Results []TopicResult `json:"results"`
}

type TopicResult struct {
	Topic string `json:"topic"`
	Count int64  `json:"count"`
}

type VoteRequest struct {
	Topics []string `json:"topics"`
}

type VoteResponse struct {
	Success bool          `json:"success"`
	Message string        `json:"message"`
	Results []TopicResult `json:"results"`
}
