// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/vote.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单个话题的投票结果
type TopicResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`  // 话题名称，如 "Go", "K8s", "AI"
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // 当前票数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicResult) Reset() {
	*x = TopicResult{}
	mi := &file_proto_vote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicResult) ProtoMessage() {}

func (x *TopicResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicResult.ProtoReflect.Descriptor instead.
func (*TopicResult) Descriptor() ([]byte, []int) {
	return file_proto_vote_proto_rawDescGZIP(), []int{0}
}

func (x *TopicResult) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TopicResult) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户 ID（从 HTTP Header X-User-Id 透传）
	Topics        []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`               // 本次投票的话题列表，可投多个
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_proto_vote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_vote_proto_rawDescGZIP(), []int{1}
}

func (x *VoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VoteRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 错误或提示信息
	Results       []*TopicResult         `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`  // 投票后的最新结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_proto_vote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_vote_proto_rawDescGZIP(), []int{2}
}

func (x *VoteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VoteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VoteResponse) GetResults() []*TopicResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户 ID
	Topics        []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`               // 要撤销的话题列表，为空则撤销全部
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_proto_vote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_proto_vote_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Results       []*TopicResult         `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"` // 撤销后的最新结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_proto_vote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_proto_vote_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RevokeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RevokeResponse) GetResults() []*TopicResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetResultsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 可选：指定查询哪些话题；为空则返回全部
	Topics        []string `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultsRequest) Reset() {
	*x = GetResultsRequest{}
	mi := &file_proto_vote_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultsRequest) ProtoMessage() {}

func (x *GetResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vote_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultsRequest.ProtoReflect.Descriptor instead.
func (*GetResultsRequest) Descriptor() ([]byte, []int) {
	return file_proto_vote_proto_rawDescGZIP(), []int{5}
}

func (x *GetResultsRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type GetResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TopicResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultsResponse) Reset() {
	*x = GetResultsResponse{}
	mi := &file_proto_vote_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultsResponse) ProtoMessage() {}

func (x *GetResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vote_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultsResponse.ProtoReflect.Descriptor instead.
func (*GetResultsResponse) Descriptor() ([]byte, []int) {
	return file_proto_vote_proto_rawDescGZIP(), []int{6}
}

func (x *GetResultsResponse) GetResults() []*TopicResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetUserVotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserVotesRequest) Reset() {
	*x = GetUserVotesRequest{}
	mi := &file_proto_vote_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserVotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserVotesRequest) ProtoMessage() {}

func (x *GetUserVotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vote_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserVotesRequest.ProtoReflect.Descriptor instead.
func (*GetUserVotesRequest) Descriptor() ([]byte, []int) {
	return file_proto_vote_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserVotesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserVotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VotedTopics   []string               `protobuf:"bytes,1,rep,name=voted_topics,json=votedTopics,proto3" json:"voted_topics,omitempty"` // 该用户已投的话题列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserVotesResponse) Reset() {
	*x = GetUserVotesResponse{}
	mi := &file_proto_vote_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserVotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserVotesResponse) ProtoMessage() {}

func (x *GetUserVotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vote_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserVotesResponse.ProtoReflect.Descriptor instead.
func (*GetUserVotesResponse) Descriptor() ([]byte, []int) {
	return file_proto_vote_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserVotesResponse) GetVotedTopics() []string {
	if x != nil {
		return x.VotedTopics
	}
	return nil
}

var File_proto_vote_proto protoreflect.FileDescriptor

const file_proto_vote_proto_rawDesc = "" +
	"\n" +
	"\x10proto/vote.proto\x12\x04vote\"9\n" +
	"\vTopicResult\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\">\n" +
	"\vVoteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\"o\n" +
	"\fVoteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\aresults\x18\x03 \x03(\v2\x11.vote.TopicResultR\aresults\"@\n" +
	"\rRevokeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\"q\n" +
	"\x0eRevokeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\aresults\x18\x03 \x03(\v2\x11.vote.TopicResultR\aresults\"+\n" +
	"\x11GetResultsRequest\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\"A\n" +
	"\x12GetResultsResponse\x12+\n" +
	"\aresults\x18\x01 \x03(\v2\x11.vote.TopicResultR\aresults\".\n" +
	"\x13GetUserVotesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"9\n" +
	"\x14GetUserVotesResponse\x12!\n" +
	"\fvoted_topics\x18\x01 \x03(\tR\vvotedTopics2\xf9\x01\n" +
	"\vVoteService\x12-\n" +
	"\x04Vote\x12\x11.vote.VoteRequest\x1a\x12.vote.VoteResponse\x123\n" +
	"\x06Revoke\x12\x13.vote.RevokeRequest\x1a\x14.vote.RevokeResponse\x12?\n" +
	"\n" +
	"GetResults\x12\x17.vote.GetResultsRequest\x1a\x18.vote.GetResultsResponse\x12E\n" +
	"\fGetUserVotes\x12\x19.vote.GetUserVotesRequest\x1a\x1a.vote.GetUserVotesResponseB\x19Z\x17vote-demo/grpcserver/pbb\x06proto3"

var (
	file_proto_vote_proto_rawDescOnce sync.Once
	file_proto_vote_proto_rawDescData []byte
)

func file_proto_vote_proto_rawDescGZIP() []byte {
	file_proto_vote_proto_rawDescOnce.Do(func() {
		file_proto_vote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vote_proto_rawDesc), len(file_proto_vote_proto_rawDesc)))
	})
	return file_proto_vote_proto_rawDescData
}

var file_proto_vote_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_vote_proto_goTypes = []any{
	(*TopicResult)(nil),          // 0: vote.TopicResult
	(*VoteRequest)(nil),          // 1: vote.VoteRequest
	(*VoteResponse)(nil),         // 2: vote.VoteResponse
	(*RevokeRequest)(nil),        // 3: vote.RevokeRequest
	(*RevokeResponse)(nil),       // 4: vote.RevokeResponse
	(*GetResultsRequest)(nil),    // 5: vote.GetResultsRequest
	(*GetResultsResponse)(nil),   // 6: vote.GetResultsResponse
	(*GetUserVotesRequest)(nil),  // 7: vote.GetUserVotesRequest
	(*GetUserVotesResponse)(nil), // 8: vote.GetUserVotesResponse
}
var file_proto_vote_proto_depIdxs = []int32{
	0, // 0: vote.VoteResponse.results:type_name -> vote.TopicResult
	0, // 1: vote.RevokeResponse.results:type_name -> vote.TopicResult
	0, // 2: vote.GetResultsResponse.results:type_name -> vote.TopicResult
	1, // 3: vote.VoteService.Vote:input_type -> vote.VoteRequest
	3, // 4: vote.VoteService.Revoke:input_type -> vote.RevokeRequest
	5, // 5: vote.VoteService.GetResults:input_type -> vote.GetResultsRequest
	7, // 6: vote.VoteService.GetUserVotes:input_type -> vote.GetUserVotesRequest
	2, // 7: vote.VoteService.Vote:output_type -> vote.VoteResponse
	4, // 8: vote.VoteService.Revoke:output_type -> vote.RevokeResponse
	6, // 9: vote.VoteService.GetResults:output_type -> vote.GetResultsResponse
	8, // 10: vote.VoteService.GetUserVotes:output_type -> vote.GetUserVotesResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_vote_proto_init() }
func file_proto_vote_proto_init() {
	if File_proto_vote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vote_proto_rawDesc), len(file_proto_vote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vote_proto_goTypes,
		DependencyIndexes: file_proto_vote_proto_depIdxs,
		MessageInfos:      file_proto_vote_proto_msgTypes,
	}.Build()
	File_proto_vote_proto = out.File
	file_proto_vote_proto_goTypes = nil
	file_proto_vote_proto_depIdxs = nil
}
