// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: vote.proto

package voteservice

import (
	"context"

	"vote-demo/grpcserver/pb/vote-demo/grpcserver/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetResultsRequest    = pb.GetResultsRequest
	GetResultsResponse   = pb.GetResultsResponse
	GetUserVotesRequest  = pb.GetUserVotesRequest
	GetUserVotesResponse = pb.GetUserVotesResponse
	RevokeRequest        = pb.RevokeRequest
	RevokeResponse       = pb.RevokeResponse
	TopicResult          = pb.TopicResult
	VoteRequest          = pb.VoteRequest
	VoteResponse         = pb.VoteResponse

	VoteService interface {
		// 投票（幂等：同一用户同一话题重复调用不会多计）
		Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
		// 撤销投票
		Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error)
		// 查询所有话题的实时票数
		GetResults(ctx context.Context, in *GetResultsRequest, opts ...grpc.CallOption) (*GetResultsResponse, error)
		// 查询某用户已投的话题（用于前端回显状态）
		GetUserVotes(ctx context.Context, in *GetUserVotesRequest, opts ...grpc.CallOption) (*GetUserVotesResponse, error)
	}

	defaultVoteService struct {
		cli zrpc.Client
	}
)

func NewVoteService(cli zrpc.Client) VoteService {
	return &defaultVoteService{
		cli: cli,
	}
}

// 投票（幂等：同一用户同一话题重复调用不会多计）
func (m *defaultVoteService) Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	client := pb.NewVoteServiceClient(m.cli.Conn())
	return client.Vote(ctx, in, opts...)
}

// 撤销投票
func (m *defaultVoteService) Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error) {
	client := pb.NewVoteServiceClient(m.cli.Conn())
	return client.Revoke(ctx, in, opts...)
}

// 查询所有话题的实时票数
func (m *defaultVoteService) GetResults(ctx context.Context, in *GetResultsRequest, opts ...grpc.CallOption) (*GetResultsResponse, error) {
	client := pb.NewVoteServiceClient(m.cli.Conn())
	return client.GetResults(ctx, in, opts...)
}

// 查询某用户已投的话题（用于前端回显状态）
func (m *defaultVoteService) GetUserVotes(ctx context.Context, in *GetUserVotesRequest, opts ...grpc.CallOption) (*GetUserVotesResponse, error) {
	client := pb.NewVoteServiceClient(m.cli.Conn())
	return client.GetUserVotes(ctx, in, opts...)
}
