// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: vote.proto

package server

import (
	"context"

	"vote-demo/grpcserve/internal/logic"
	"vote-demo/grpcserve/internal/svc"
	"vote-demo/grpcserver/pb/vote-demo/grpcserver/pb"
)

type VoteServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedVoteServiceServer
}

func NewVoteServiceServer(svcCtx *svc.ServiceContext) *VoteServiceServer {
	return &VoteServiceServer{
		svcCtx: svcCtx,
	}
}

// 投票（幂等：同一用户同一话题重复调用不会多计）
func (s *VoteServiceServer) Vote(ctx context.Context, in *pb.VoteRequest) (*pb.VoteResponse, error) {
	l := logic.NewVoteLogic(ctx, s.svcCtx)
	return l.Vote(in)
}

// 撤销投票
func (s *VoteServiceServer) Revoke(ctx context.Context, in *pb.RevokeRequest) (*pb.RevokeResponse, error) {
	l := logic.NewRevokeLogic(ctx, s.svcCtx)
	return l.Revoke(in)
}

// 查询所有话题的实时票数
func (s *VoteServiceServer) GetResults(ctx context.Context, in *pb.GetResultsRequest) (*pb.GetResultsResponse, error) {
	l := logic.NewGetResultsLogic(ctx, s.svcCtx)
	return l.GetResults(in)
}

// 查询某用户已投的话题（用于前端回显状态）
func (s *VoteServiceServer) GetUserVotes(ctx context.Context, in *pb.GetUserVotesRequest) (*pb.GetUserVotesResponse, error) {
	l := logic.NewGetUserVotesLogic(ctx, s.svcCtx)
	return l.GetUserVotes(in)
}
